### ISSUE TITLE
Replace Starboard with AGIMUS reaction handling

### ISSUE THREAD

**Issue by zmattingly** [jp00p/AGIMUS#101]
Soon AGIMUS shall replace functionality and be the ONLY BOT STANDING!!! Praise AGIMUS!

**Comment by jp00p** [comment]
starboard functionality is in and seems to be functioning well enough!

it does seem a bit slow, i think mostly because it has to do an async call to get all the users of each reaction.  if there's a way to speed that up i would love it!
