### ISSUE TITLE
Bug: Taglines currently have no char limit, or it is too large

### ISSUE THREAD

**Issue by mathew-fleisch** [jp00p/AGIMUS#246]
```
/set_tagline tagline: abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz
```
Looks like the character limit should be about 50 characters.

![profile-bug](https://user-images.githubusercontent.com/961978/183215160-d291d238-34ca-4c52-9ad3-9122fb293dc2.png)

**Comment by bhammerslag** [comment]
Are we OK just trimming the input to 50 characters, or do we want to reject it entirely and send a message?
