### ISSUE TITLE
Feat: badge look-up command

### ISSUE THREAD

**Issue by mathew-fleisch** [jp00p/AGIMUS#248]
Use autocomplete menu to auto-fill the argument in this potential slash command
`/badge lookup [badge-name]`
Display badge image and link out to website for more information:
https://startrekdesignproject.com/symbols/starfleet-2280s-informal/

This should probably be an ephemeral message response by default.

**Comment by mathew-fleisch** [comment]
Use `/info` command as inspiration/template

**Comment by danmatakizawa** [comment]
We made it go and it went out!
