### ISSUE TITLE
Specify a License

### ISSUE THREAD

**Issue by mosengmr** [jp00p/AGIMUS#448]
I noticed there is not a license listed anywhere (that I saw), nor does the repo have a LICENSE file.  I don't know if that was intentional, but if it wasn't, it would be nice to actually specify a license (even if it's just [The Unlicense](https://choosealicense.com/licenses/unlicense/)).  Otherwise, things can get really weird really quick, legally speaking.

**Comment by zmattingly** [comment]
Addressed with #535
