### ISSUE TITLE
Switch to py-cord, and/or use 'bot.commands' 

### ISSUE THREAD

**Issue by zmattingly** [jp00p/AGIMUS#96]
Would be some hefty work but `discord.py` is technically no longer in active development and [py-cord](https://docs.pycord.dev/en/master/ext/commands/index.html) is the new hotness and a fork of the original `discord.py`

If we want to use additional features we should maybe look into switching over and converting our command handlers to the [`bot.commands` paradigm](https://docs.pycord.dev/en/master/api.html#discord.Bot).

Would give us access to stuff like the [Discord Bot UI kit](https://docs.pycord.dev/en/master/api.html#bot-ui-kit) and the [Button interface](https://docs.pycord.dev/en/master/api.html#button).

**Comment by jp00p** [comment]
i'd say we are done here!
