### ISSUE TITLE
Scale Usernames in Profile Cards

### ISSUE THREAD

**Issue by zmattingly** [jp00p/AGIMUS#99]
Long usernames currently get cut off on the profile cards. We could add something to check the length of the string and then scale the text down appropriately (to a certain limit at which point we could probably just add an elipses for the rest if it's _really_ long).

**Comment by jp00p** [comment]
may have found a solution here https://stackoverflow.com/questions/70415348/how-do-i-anchor-text-and-shrink-it-to-fit-it-on-an-image

**Comment by jp00p** [comment]
new profiles make this somewhat irrelevant but still could be an issue if someone has a verrrrrrry long name
